import type { ActiveProfile } from "./suggestionTypes";
import type { KnowledgeEntry } from "./knowledgeTypes";

export const DEFAULT_PROFILE_ID = "profile_demo";

export const DEFAULT_PROFILE: ActiveProfile = {
  id: DEFAULT_PROFILE_ID,
  name: "Benedikt Peterson",
  sensitivity: "normal",
};

export const DEFAULT_ENTRIES: KnowledgeEntry[] = [
  {
    id: "entry_personal_full_name",
    profileId: DEFAULT_PROFILE_ID,
    label: "full name",
    value: "Benedikt Peterson",
    summary: "Primary full legal name",
    tags: ["name", "identity"],
    sourceId: "source_profile_manual",
    sourceLabel: "Manual profile entry",
    sensitivity: "normal",
  },
  {
    id: "entry_personal_first_name",
    profileId: DEFAULT_PROFILE_ID,
    label: "first name",
    value: "Benedikt",
    tags: ["first name", "given name", "forename", "vorname"],
    aliases: ["given name", "forename", "Vorname"],
    sourceId: "source_profile_manual",
    sourceLabel: "Manual profile entry",
    sensitivity: "normal",
  },
  {
    id: "entry_personal_last_name",
    profileId: DEFAULT_PROFILE_ID,
    label: "last name",
    value: "Peterson",
    tags: ["last name", "family name", "surname", "nachname"],
    aliases: ["family name", "surname", "Nachname"],
    sourceId: "source_profile_manual",
    sourceLabel: "Manual profile entry",
    sensitivity: "normal",
  },
  {
    id: "entry_personal_salutation",
    profileId: DEFAULT_PROFILE_ID,
    label: "salutation",
    value: "Herr",
    tags: ["salutation", "title", "anrede", "mr"],
    aliases: ["Anrede", "title", "Mr", "Mister"],
    sourceId: "source_profile_manual",
    sourceLabel: "Manual profile entry",
    sensitivity: "normal",
  },
  {
    id: "entry_personal_gender",
    profileId: DEFAULT_PROFILE_ID,
    label: "gender",
    value: "männlich",
    tags: ["gender", "sex", "geschlecht", "male"],
    aliases: ["Geschlecht", "sex", "male", "man"],
    sourceId: "source_profile_manual",
    sourceLabel: "Manual profile entry",
    sensitivity: "sensitive",
  },
  {
    id: "entry_personal_email",
    profileId: DEFAULT_PROFILE_ID,
    label: "email address",
    value: "ben@gmail.com",
    summary: "Primary contact email",
    tags: ["email", "contact", "e-mail", "mail"],
    aliases: ["E-Mail", "Email", "E-Mail-Adresse", "Email address", "Mail"],
    sourceId: "source_profile_manual",
    sourceLabel: "Manual profile entry",
    sensitivity: "sensitive",
  },
  {
    id: "entry_personal_phone",
    profileId: DEFAULT_PROFILE_ID,
    label: "phone number",
    value: "+124712794798",
    summary: "Primary phone number",
    tags: ["phone", "contact", "telephone", "mobile"],
    aliases: [
      "Telefon",
      "Telefonnummer",
      "Mobil",
      "Mobilnummer",
      "Phone",
      "Phone number",
      "Telephone",
    ],
    sourceId: "source_profile_manual",
    sourceLabel: "Manual profile entry",
    sensitivity: "sensitive",
  },
  {
    id: "entry_address_street",
    profileId: DEFAULT_PROFILE_ID,
    label: "street address",
    value: "Hauptstr. 1",
    tags: ["address", "street", "street address", "anschrift", "straße"],
    aliases: [
      "address line 1",
      "street and house number",
      "Straße und Hausnummer",
    ],
    sourceId: "source_profile_manual",
    sourceLabel: "Manual profile entry",
    sensitivity: "sensitive",
  },
  {
    id: "entry_address_street_name",
    profileId: DEFAULT_PROFILE_ID,
    label: "street name",
    value: "Hauptstr.",
    tags: ["street", "street name", "straße"],
    aliases: ["Straße"],
    sourceId: "source_profile_manual",
    sourceLabel: "Manual profile entry",
    sensitivity: "sensitive",
  },
  {
    id: "entry_address_house_number",
    profileId: DEFAULT_PROFILE_ID,
    label: "house number",
    value: "1",
    tags: ["house number", "street number", "hausnummer"],
    aliases: ["Hausnummer"],
    sourceId: "source_profile_manual",
    sourceLabel: "Manual profile entry",
    sensitivity: "sensitive",
  },
  {
    id: "entry_address_postal_code",
    profileId: DEFAULT_PROFILE_ID,
    label: "postal code",
    value: "13344",
    tags: ["postal code", "postcode", "zip", "zip code", "plz"],
    aliases: ["ZIP code", "Postleitzahl", "PLZ"],
    sourceId: "source_profile_manual",
    sourceLabel: "Manual profile entry",
    sensitivity: "sensitive",
  },
  {
    id: "entry_address_city",
    profileId: DEFAULT_PROFILE_ID,
    label: "city",
    value: "Berlin",
    tags: ["city", "town", "location", "ort", "stadt"],
    aliases: ["town", "Ort", "Stadt"],
    sourceId: "source_profile_manual",
    sourceLabel: "Manual profile entry",
    sensitivity: "sensitive",
  },
  {
    id: "entry_address_country",
    profileId: DEFAULT_PROFILE_ID,
    label: "country",
    value: "Deutschland",
    tags: ["country", "country of residence", "land", "germany", "de"],
    aliases: ["Germany", "DE", "Land"],
    sourceId: "source_profile_manual",
    sourceLabel: "Manual profile entry",
    sensitivity: "normal",
  },
  {
    id: "entry_address_full",
    profileId: DEFAULT_PROFILE_ID,
    label: "full address",
    value: "Hauptstr. 1, 13344 Berlin, Deutschland",
    tags: ["full address", "mailing address", "postal address", "anschrift"],
    aliases: ["mailing address", "postal address", "Anschrift"],
    sourceId: "source_profile_manual",
    sourceLabel: "Manual profile entry",
    sensitivity: "sensitive",
  },
];
